# permissions for end users to edit webhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: webhook-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oadp-operator
    app.kubernetes.io/part-of: oadp-operator
    app.kubernetes.io/managed-by: kustomize
  name: webhook-editor-role
rules:
- apiGroups:
  - nac.oadp.openshift.io
  resources:
  - webhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nac.oadp.openshift.io
  resources:
  - webhooks/status
  verbs:
  - get
